# Generated by Django 3.1.5 on 2021-01-16 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='email',
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='medico',
            name='telefone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.especialidade'),
        ),
    ]
