# Generated by Django 3.1.5 on 2021-01-16 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_agenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='horario',
            new_name='horarios',
        ),
        migrations.AddField(
            model_name='agenda',
            name='dia',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('medico', 'dia')},
        ),
        migrations.AlterIndexTogether(
            name='agenda',
            index_together={('medico', 'dia')},
        ),
    ]
