# Generated by Django 3.1.5 on 2021-01-17 02:42

import api.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210116_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.DateField(default=datetime.date.today, validators=[api.validators.validate_present_or_future]),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horarios',
            field=models.ManyToManyField(blank=True, to='api.Horario'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horario', models.TimeField()),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico')),
            ],
        ),
    ]
